### PR TITLE
WIP: Add conversion from LAMMPS data file to Particles

### PR DESCRIPTION
**Pull request by nathanfranklin**
PR adds conversion method to read a LAMMPS data file and convert to a list of `Particles`. 

For example:

```
particles_list = read_data_file("example.data")
```

### CODE REVIEW

**Comment by nathanfranklin** [comment]
@TobiasRasp, here is what i had so far.

**Comment by nathanfranklin** [comment]
@TobiasRasp , @ahashibon @mehdisadeghi ,  this is ready to be reviewed/merged

**Comment by TobiasRasp** [comment]
It would be beneficial, if the CUBA-Extension attributes BOX_VECTORS and BOX_ORIGIN were also extracted from the native LAMMPS data file by the conversion tool. The information needed is in the header of the LAMMPS file.

**Comment by nathanfranklin** [comment]
@TobiasRasp, the BOX_VECTORS and BOX_ORIGIN are now added.

**Comment by TobiasRasp** [comment]
Good to merge, works!

**Pull request merged**
